spring.application.name=memo-app
server.port=8080

spring.datasource.url=${SPRING_DATASOURCE_URL:-jdbc:mysql://localhost:3306/memodb}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:-memo}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:-memo}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

cors.allowed-origins=${CORS_ALLOWED_ORIGINS:*}
